"""Added company name to User

Revision ID: 0ad55f90d8a9
Revises: 329abe600c8f
Create Date: 2018-09-14 18:23:20.322640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad55f90d8a9'
down_revision = '329abe600c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company_name')
    # ### end Alembic commands ###
