"""Added User Table

Revision ID: 59edc84c24bb
Revises: 761e9a963aa2
Create Date: 2018-09-13 09:54:43.895182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59edc84c24bb'
down_revision = '761e9a963aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=140), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
